### PR TITLE
Merge Feature/methods, enumerable methods completed

### PR DESCRIPTION
**Pull request by sebGilR**
The project has been completed following GitFlow and based on the requirements. All methods were tested and are working.

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @sebGilR        
#### Great Job so far, but there are a few more things required. 
### General
- [x] Let fix this broken link 

- [x] Pull Request has a meaningful title and short description 
 - [x] Kindly enable stickler for this project.
- [x] Kindly refer to this doc for guidance https://ruby-doc.org/core-2.6.5/Enumerable.html 
- [x] `my_each` 
-  returns an Enumerator if no block is given:
  `p [1, 2, 3].my_each` returns `#<Enumerator>`
- calls the given block once for each element in self
  `my_each_output = '' `
 `my_each_output_two = '' `
  `block = proc { |y| my_each_output += "Hello: #{y}" }`
  `block_two = proc { |y| my_each_output_two += "Hello: #{y}" }`
  `[1,2,32,32,3,21,1,23,12].each(&block_two)`
  `[1,2,32,32,3,21,1,23,12].my_each(&block)`
   `p my_each_output ==  my_each_output_two` should return `true`

- [x] `my_each_with_index`  
- returns an Enumerator if no block is given:
  `p [1, 2, 3].my_each_with_index` returns `#<Enumerator>`

- [x] `my_all`  
- returns true if the block never returns false or nil
  `  block =  proc { |num| num < 20 } `
    `  p [2,32,32].my_all?(&block)  `should return `false`
- when no block or argument is given returns true when none of the collection members are false or nil:
 `p [1, true, 'hi', []].my_all?` should return `true`.
- when a class is passed as an argument returns true if all of the collection is a member of such class
`p [1,1,1].my_all?(Integer)` should return `true`
-  when a Regex is passed as an argument returns true if all of the collection matches the Regex
`p ['d','d'].my_all?(/d/)` should return `true`
- when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
`p [3,3,3,3].my_all?(3)` should return `true`


- [x] `my_any?`:
- returns true if the block ever returns a value other than false or nil
`block = proc { |num| num <= 3 }`
`p [12,12,13,4].my_any?(&block)` should return `false`

- when no block or argument is given returns true if at least one of the collection is not false or nil
`p [nil, false, nil, false].my_any?` - should return `false`
- when a class is passed as an argument returns true if at least one of the collection is a member of such class
`p [12,3,34].my_any?(Integer)` should return `true`
- when a Regex is passed as an argument returns false if none of the collection matches the Regex
`p ['ghetto','wild'].my_any?(/z/)` should return `false`
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
`p ['cat',2,32,].my_any?('cat')` should return `true`

- [x] `my_none?`:
- returns true if the block never returns true for all elements
`block = proc { |num| num < 2 }`
`p [2,23,21,12].my_none?(&block)` should return true
- When no block or argument is given returns true only if none of the collection members is true
`p  [nil, false, true, []].my_none?`  should return `false`
- When a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
`p ['hello'].my_none?(5)` - should return `true`
- when a class is passed as an argument returns true if none of the collection is a member of such class
`p [3,3,3,3].my_none?(String)`  should return `true`
- when a Regex is passed as an argument returns true only if none of the collection matches the Regex
`p ['hello','milk','milo'].my_none?(/z/)` should return `true`



- [x] `my_count`
- counts the number of items in enum that are equal to item if an argument is given:
`p [1, 2, 3,2].my_count(2)` should return `2`
-  counts the number of elements yielding a true value if a block is given
`block = proc { |num| num < (2 + 24) / 2 }`
`p [23,13,12,43].my_count(&block)` should return 1
- [x] `my_map` 
- returns an Enumerator if no block is given:
  `p [1, 2, 3].my_map` returns `#<Enumerator>`
- returns a new array with the results of running block once for every element in enum.
`block = proc { |num| num < (2 + 7) / 2 }`
`p [22,4,3,42,43].my_map(&block)` should return `[false, false, true, false, false]`
- [x] `my_inject`:
- When a symbol is specified combines each element of the collection by applying the symbol as a named method
`p (5..10).my_inject(2, :*)`  should return 302400`
- Combines all elements of enum by applying a binary operation, specified by a block:
 `p (1..5).my_inject(4) { |prod, n| prod * n }` should return 480

- [x] `my_select`  
- returns an Enumerator if no block is given:
  `p [1, 2, 3].my_select` returns `#<Enumerator>`
- returns an array containing all elements of enum for which the given block returns a true value
`block = proc { |num| num < 24 }`
`p [23,13,12,43].my_select(&block)` should return [23, 13, 12]





### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by sebGilR** [comment]
Changes requested by TSE have been implemented. All methods functionalities have been tested and README file was updated.

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Sebastian!  
### Your did amazing job correcting errors pointed previously :+1: 
Just a few more changes needed:
* [x] `my_each` should return an Enumerator if no block is given:
`[1, 2, 3].my_each` should return `#<Enumerator: [1, 2, 3]:my_each>`
* [x] `my_select` should return an Enumerator if no block is given:
`[1, 2, 3].my_select` should return `#<Enumerator: [1, 2, 3]:my_select>`
* [x] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)) 
[Here](https://github.com/microverseinc/linters-config/tree/master/ruby) you can find all information about how to setup linter for Ruby curriculum.
### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by sebGilR** [comment]
Changes to return enumerator done.

Changes to the linter suggested by Microverse guidelines for this project, not changed.
image

**Comment by Anna-Myzukina** [comment]
# Status: [APPROVED]


### Go ahead and merge to master.


#### Goodluck in your next project Happy coding <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
